### ISSUE TITLE
Put Bucket Versioning

### ISSUE THREAD

**Issue by shaopu1225** [Nugine/s3s#103]
AWS s3api allows enable/suspend bucket versioning. Currently, I am using s3s-fs to perform local simulation, and I found the s3s-fs does not support put_bucket_versioning. Since all the buckets are stored as a file locally, I am confused how to achieve this functionality?

**Comment by Nugine** [comment]
Simulating all S3 functionality needs a great architecture and lots of work. The internal metadata part of `s3s-fs` is naive. So it's relatively difficult to add some APIs beyond the basic ones. We may refactor `s3s-fs` in the future.

**Comment by shaopu1225** [comment]
Get it, thanks!
