### ISSUE TITLE
Suggestion: Add AccessKey / user information to S3 trait methods

### ISSUE THREAD

**Issue by St4NNi** [Nugine/s3s#16]
Hi, thanks for building this crate, very useful for building our own s3 compatible interface!
 
Unfortunately we had issues while experimenting with you S3_trait methods, because these methods lack any identity information about the user who issued the request. Would it be possible to add these information to the S3 trait ?

One suggestion would be to add the access_key to each method like this:

```rust
async fn abort_multipart_upload(&self, _input: AbortMultipartUploadInput, _access_key: String) -> S3Result<AbortMultipartUploadOutput> {
        Err(s3_error!(NotImplemented, "AbortMultipartUpload is not implemented yet"))
}
```

This would allow us to change or validate backend behavior based on identity information.

**Comment by St4NNi** [comment]
Very nice, thanks a lot for the addition. We will try to implement / integrate this now.

**Comment by St4NNi** [comment]
Hi, just to give you a quick heads-up: In our preliminary tests everything worked as expected, especially in combination with a custom auth provider. From my side you are good to go for a v0.4.0 release. Thanks again for the addition, will make our work a lot easier !

**Comment by Nugine** [comment]
s3s v0.4.0 is now released!
