### ISSUE TITLE
S3s also has an admin-api, websocket rpc, sharing a listener

### ISSUE THREAD

**Issue by loverustfs** [Nugine/s3s#173]
Is it possible to add an Admin API to s3s and share the websocket rpc?

There are several benefits:

This makes it easier to read and write objects from other remote nodes, and to implement distributed reading and writing;
s3 service adapter users can freely implement some S3 management functions;

是否可以在s3s 中加上一套 Admin API，并且共用websocket 的rpc？

有以下几个好处：

这样在读写远程其他Node的对象实更方便，更方便的实现分布式读写；
s3 service adapter 用户可以自由实现一些S3的管理功能；

**Comment by Nugine** [comment]
Implemented in #209.

See also
+ #195 
+ #166
