### ISSUE TITLE
CompleteMultipartUpload Request body error

### ISSUE THREAD

**Issue by lperlaki** [Nugine/s3s#2]
I found a bug in the XML parsing for the complete-multipart-upload operation.

the root object should have the name `CompleteMultipartUpload` but is `CompletedMultipartUpload`

```diff
// src/ops/generated.rs:11490
impl<'xml> xml::Deserialize<'xml> for CompletedMultipartUpload {
    fn deserialize(d: &mut xml::Deserializer<'xml>) -> xml::DeResult<Self> {
-        d.named_element("CompletedMultipartUpload", |d| d.content())
+        d.named_element("CompleteMultipartUpload", |d| d.content())
    }
}
```

I am not that familiar with the code generator maybe you could give me some directions and I could make a pull request

**Comment by Nugine** [comment]
Thanks! I have just updated the readme and added some guides. I'm looking into this bug right now.
