### ISSUE TITLE
I created s3d.rs not long ago with a very similar idea, and I am very happy to see s3s doing much more ...

### ISSUE THREAD

**Issue by guymguym** [Nugine/s3s#33]
Hi @Nugine - Nice to gh-meet you and see this project!

I created https://s3d.rs (https://github.com/s3d-rs/s3d) last year and haven't been able to push through enough, so it got stalled. I was very excited to see how s3s is built, and as I was reading through the code I could see similar questions I had too (like using smithy-rs codegen-server to generate code vs reading the model and generating with native rust code). I am also the creator of noobaa which is yet another S3 service written in nodejs and c++ (https://github.com/noobaa/noobaa-core).

I would be happy to find ways to help this project! All the best. Guy

**Comment by Nugine** [comment]
Yeah. We can build awesome things together!

s3d helps me a lot when I started investigating custom codegen implementation. I'm sure I cannot launch s3s project without the previous work of s3d. Thank you!

Here are some entry points:
+ [Development Guide](https://github.com/Nugine/s3s/blob/main/CONTRIBUTING.md)
+ [Todo List](https://github.com/Nugine/s3s/issues/1)
+ [CI workflow](https://github.com/Nugine/s3s/blob/main/.github/workflows/ci.yml)

#### Project History

AFAIK, [datenlord/s3-server](https://github.com/datenlord/s3-server) is the first Rust library to provide S3 server-side api, launched on 2020-08-04.

[awslabs/smithy-rs](https://github.com/awslabs/smithy-rs) launched on 2020-10-28, [awslabs/aws-sdk-rust](https://github.com/awslabs/aws-sdk-rust) on 2021-04-13.

[rusoto](https://github.com/rusoto/rusoto) lost maintenance soon after the offical sdk was out, which caused some trouble.

[s3d-rs/s3d](https://github.com/s3d-rs/s3d/) launched on 2021-10-14 and stopped update on 2022-05-13.

Finally, [s3s](https://github.com/Nugine/s3s) launched on [2023-01-11](https://github.com/datenlord/s3-server/issues/108#issuecomment-1378983511), as the successor of s3-server.
