### ISSUE TITLE
S3 and turmoil

### ISSUE THREAD

**Issue by mcches** [Nugine/s3s#70]
Hiya! I'm one of the contributors on [turmoil](https://github.com/tokio-rs/turmoil) and it seems like we could enable running this within turmoil fixtures pretty easily. Is this something you'd all be interested in?

We already have support for hyper using turmoil transport: https://github.com/tokio-rs/turmoil/blob/main/examples/axum/src/main.rs

**Comment by Nugine** [comment]
`s3s` has a special case that can run integration tests without network connections or listening to any port. We connect the `aws-sdk-s3` client and the S3 service directly.
https://github.com/Nugine/s3s/blob/5cc2168a70274395b3187a2370f14a7482660805/crates/s3s-fs/tests/it_aws.rs#L69-L78

`turmoil` is an awesome project. I'll try it when we start to test concurrency bugs.
Thank you!
