### ISSUE TITLE
Feature Request: Support Checksums

### ISSUE THREAD

**Issue by nivista** [Nugine/s3s#72]
Hi, 

We are trying to use s3s-fs for integration testing. We use crc32_c to verify the integrity of our objects when we do PutObject and GetObject.

https://docs.aws.amazon.com/AmazonS3/latest/userguide/checking-object-integrity.html

Could s3s-fs support this feature?

**Comment by Nugine** [comment]
> Could s3s-fs support this feature?

Yes. Could you provide more information or code about how you use checksums?

**Comment by nivista** [comment]
We provide a computed checksum in the put object request. When we do get object we verify the checksum in the response to ensure content integrity. This is just an additional measure for content integrity on top of what s3 already does. We expect to get the checksum in the get object response when we pass the `.checksum_mode(ChecksumMode::Enabled)` option to the SDK (after we provided it in the initial put object request).
